### ISSUE TITLE
How to shutdown nodes?

### ISSUE THREAD

**Issue by NoobTitan** [CodeFinder2/roslaunch2#1]
Thanks for the wonderful work!

Is there one way to start nodes or terminate nodes freely?

**Comment by CodeFinder2** [comment]
Sorry for replying so late, thanks for your issue and glad that you find this useful! :-)

There is, although it's probably not that convenient. You could write a Python script, say `python_script.py`, that uses the roslaunch2 API to start nodes placed in a roslaunch2 launch module (.pyl). That is, say you want to start a node `A`, then you could create a file, say `node_A.pyl`, which just starts node `A` (see this [example](https://github.com/CodeFinder2/roslaunch2/blob/master/launch/simple_example.pyl#L30)). In your `python_script.py` file, you do `import roslaunch2` and start it by
```py
import roslaunch2
# ...
your_pkg = roslaunch2.Package('name_of_your_package')
p = roslaunch2.start_async(your_pkg.use('node_A'))
# ...
p.terminate()
```

Since this uses async start, your cflow continues after the start and you can do whatever you want to do or check appropriate conditions for termination of your node `A`. To finally terminate it, call `p.terminate()` (see snippet).

Theoretically, this could again be a launch module itself (although it may not be useful at first sight).

Hope this helps! :-)

**Comment by CodeFinder2** [comment]
I will close this for now as your questions should be answered. Feel free to reopen if you need further assistance!
